local civilianDescription = {
	--[[
    {
        text = "", -- text to be displayed
        typewriterDelay = 0.025, -- delay between each individual character
        delay = 4 -- delay until the next message is displayed
    }
    ]]
	{
		text = "You are a civilian, meaning you must assist other innocent players in uncovering who the Mafia is.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Search the grounds for anything suspicious, and report suspicious activity during discussion time.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Prevent yourself from getting eliminated by hiding in certain areas or staying in well-lit places.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Be careful though, if you reveal yourself too much, other players may falsely suspect you as part of the Mafia.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Use perks to give yourself and your team an advantage. Communication is key.",
		typewriterDelay = 0.035,
		delay = 4,
	},
}

return civilianDescription
