local detainerDescription = {
	--[[
    {
        text = "", -- text to be displayed
        typewriterDelay = 0.025, -- delay between each individual character
        delay = 4 -- delay until the next message is displayed
    }
    ]]
	{
		text = "Your task as the Detainer is to throw people in jail during the night.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "The chosen player will be jailed and they will not be present during discussion, voting or the night after voting.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Use this ability to either save a civilian, or target a player.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "To throw a player in jail, click and cuff them during the night and they will be sent to jail.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "You have one of the most important roles in finding out who the Mafia is.",
		typewriterDelay = 0.025,
		delay = 4,
	},
}

return detainerDescription
