local detectiveDescription = {
    --[[
    {
        text = "", -- text to be displayed
        typewriterDelay = 0.025, -- delay between each individual character
        delay = 4 -- delay until the next message is displayed
    }
    ]]
    {
        text = "Your task as the Detective is to aid the civilians in discovering who the Mafia may be.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "After each night, you will get a report on people that were close to the body after each elimination.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "The report will state recent charges placed against the players along with the casualties, if any. All reports will be saved on your screen.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "You can investigate a player further if you feel the need to on the report. You can also use your magnifying glass to see players' names during the night.",
        typewriterDelay = 0.02,
        delay = 4
    },
    {
        text = "Stay aware. Do not give yourself away as the Detective.",
        typewriterDelay = 0.0275,
        delay = 4
    },
}

return detectiveDescription