local doctorDescription = {
	--[[
    {
        text = "", -- text to be displayed
        typewriterDelay = 0.025, -- delay between each individual character
        delay = 4 -- delay until the next message is displayed
    }
    ]]
	{
		text = "Your task as the Doctor is to look out for players who may have been harmed by the Mafia.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "You can save a player (who may still be alive after being attacked) by clicking on the player and healing them instantly.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Listen out for gunshots, they will reveal the area of which a player has been attacked.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Stay aware though, a player only either survives for ten seconds after an attack, or dies instantly.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Revealing yourself as the Doctor would only make you a target for the Mafia. Stay anonymous.",
		typewriterDelay = 0.025,
		delay = 4,
	},
}

return doctorDescription
