local jesterDescription = {
    --[[
    {
        text = "", -- text to be displayed
        typewriterDelay = 0.025, -- delay between each individual character
        delay = 4 -- delay until the next message is displayed
    }
    ]]
    {
        text = "Your task as the Jester is to make everyone believe you are the Mafia.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "This is so that you can get voted out during voting time, and get your revenge by striking the night after.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "As soon as you get voted out, everyone will be notified that you were the Jester.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "Get your revenge by walking around the map the night after you have been voted out. Click on a player to eliminate them.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "If you fail to get voted out, or get killed during the night, you will fail your mission.",
        typewriterDelay = 0.025,
        delay = 4
    },
}

return jesterDescription