local mafiaDescription = {
    --[[
    {
        text = "", -- text to be displayed
        typewriterDelay = 0.025, -- delay between each individual character
        delay = 4 -- delay until the next message is displayed
    }
    ]]
    {
        text = "You are part of the Mafia, meaning you must eliminate as many players as possible without getting caught in the act.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "If there are other Mafias in the game, make sure to cooperate with them to secure a win.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "To eliminate someone, creep up on them during the night and click on them to eliminate them. You will either use a gun or knife based on the distance.",
        typewriterDelay = 0.025,
        delay = 4
    },
    {
        text = "You can only eliminate one person per night. If you fail to eliminate someone, or choose not to, you can only do so twice in a row or you will be eliminated.",
        typewriterDelay = 0.02,
        delay = 4
    },
    {
        text = "Use perks to give yourself and your team an advantage. Communication is key. Do not give yourself away.",
        typewriterDelay = 0.025,
        delay = 4
    },
}

return mafiaDescription