local vigilanteDescription = {
	--[[
    {
        text = "", -- text to be displayed
        typewriterDelay = 0.025, -- delay between each individual character
        delay = 4 -- delay until the next message is displayed
    }
    ]]
	{
		text = "Your task as the Vigilante is to track down the Mafia and eliminate them during one of the nights in the game.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "At any time during the night, and discussion, you can shoot who you believe is guilty by clicking on them and restore justice.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "If you shoot the Mafia, or one of the Mafias, you stay in the game. If you shoot an innocent player, you will go down with them.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Check for suspicious activity during the night and during discussion.",
		typewriterDelay = 0.025,
		delay = 4,
	},
	{
		text = "Stay aware, do not give yourself away or you will be made a target for the Mafia.",
		typewriterDelay = 0.025,
		delay = 4,
	},
}

return vigilanteDescription
