name: Auto-Versioning

on:
  push:
    branches:
      - main

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate version
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Print Version
        run: echo "Current version is $VERSION"
